language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
notifications:
  irc:
    channels: "irc.freenode.org#writhem"
    on_success: change
    on_failure: change